# Generated by Django 5.0.7 on 2024-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_intensity', models.FloatField(blank=True, null=True)),
                ('rain_index', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('cityname', models.TextField(blank=True, null=True)),
                ('localityname', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('device_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"zomato_forecast_kf"."forecast"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadarData',
            fields=[
                ('dbz_value', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('r_mm_hr_field', models.FloatField(blank=True, db_column='R(mm/hr)', null=True)),
                ('rain_index', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"radar_data"."radar_data"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteConfigs',
            fields=[
                ('cityname', models.CharField(blank=True, max_length=50, null=True)),
                ('localityname', models.CharField(blank=True, max_length=50, null=True)),
                ('localityid', models.CharField(db_column='locationId', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"zomato_sites". "site_configs"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.TextField(blank=True, null=True)),
                ('humidity', models.TextField(blank=True, null=True)),
                ('wind_speed', models.TextField(blank=True, null=True)),
                ('wind_direction', models.TextField(blank=True, null=True)),
                ('rain_intensity', models.TextField(blank=True, null=True)),
                ('rain_accumulation', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('rain_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"zomato_new_actual"."weather_data"',
                'managed': False,
            },
        ),
    ]
