# Generated by Django 5.0.7 on 2024-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarSensorComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localityid', models.TextField(blank=True, db_column='localityId', null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('radar_rain_index', models.BigIntegerField(blank=True, null=True)),
                ('rdr_rain_intensity', models.FloatField(blank=True, null=True)),
                ('sns_rain_intensity', models.TextField(blank=True, null=True)),
                ('sns_rain_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"radar_data"."radar_sensor_comparison"',
                'managed': False,
            },
        ),
    ]
