DATABASE_HOST = "tensordb1.cn6gzof6sqbw.us-east-2.rds.amazonaws.com"
USER_NAME = "admin123"
PASSWORD = "tensor123"
PORT = "5432"
USER_SCHEMA = "new_portal"
MAPBOX_TOKEN = "pk.eyJ1IjoidmFpYmhhdnBoYXJhdGUiLCJhIjoiY2xuazFubDJnMXFtdDJrdzVhdHB5dThkYyJ9.SZBQ94MCcz7odz-WkOOs7w"
